version: '3'

networks:
  sample:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

services:
  client:
    image: centos:7
    tty: true
    stdin_open: true
    networks:
      sample:
        ipv4_address: 172.16.1.2
  web:
    build: web
    ports:
      - "10380:80"
    tty: true
    stdin_open: true
    networks:
      sample:
        ipv4_address: 172.16.1.3
  forward_proxy:
    build: forward_proxy
    ports:
      - "10480:80"
    networks:
      sample:
        ipv4_address: 172.16.1.4

