version: '3'

networks:
  sample:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

volumes:
  ca_CA:
    driver: local
  client_opt:
    driver: local
  server_ssl:
    driver: local
  reverse_proxy_ssl:
    driver: local

services:
  ca:
    build: ca
    tty: true
    stdin_open: true
    networks:
      sample:
        ipv4_address: 172.16.1.254
    volumes:
      - ca_CA:/etc/pki/CA
  client:
    build: client
    tty: true
    stdin_open: true
    links:
      - server:my-server
      - forward_proxy:my-forward-proxy
      - reverse_proxy:my-reverse-proxy
    networks:
      sample:
        ipv4_address: 172.16.1.2
    volumes:
      - client_opt:/opt/ssl
  server:
    build: server
    ports:
      - "10380:80"
    tty: true
    stdin_open: true
    networks:
      sample:
        ipv4_address: 172.16.1.3
    volumes:
      - server_ssl:/usr/local/apache2/conf/ssl/
  forward_proxy:
    build: forward_proxy
    ports:
      - "10480:80"
    links:
      - server:my-server
    networks:
      sample:
        ipv4_address: 172.16.1.4
  reverse_proxy:
    build: reverse_proxy
    ports:
      - "10580:80"
    links:
      - server:my-server
    networks:
      sample:
        ipv4_address: 172.16.1.5
    volumes:
      - reverse_proxy_ssl:/usr/local/apache2/conf/ssl/

